// <auto-generated />
using HomeBaseCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeBaseCore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180602173842_dbsets")]
    partial class dbsets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("HomeBaseCore.Models.FileData", b =>
                {
                    b.Property<int>("FileDataID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileDescription");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<int>("FolderID");

                    b.Property<int>("OwnerProfileID");

                    b.HasKey("FileDataID");

                    b.ToTable("files");
                });

            modelBuilder.Entity("HomeBaseCore.Models.FolderData", b =>
                {
                    b.Property<int>("FolderDataID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FolderDescription");

                    b.Property<string>("FolderName");

                    b.Property<string>("FolderPath");

                    b.Property<int>("OwnerProfileID");

                    b.HasKey("FolderDataID");

                    b.ToTable("folders");
                });

            modelBuilder.Entity("HomeBaseCore.Models.ProfileData", b =>
                {
                    b.Property<int>("ProfileDataID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("ProfileGuid");

                    b.Property<string>("Username");

                    b.HasKey("ProfileDataID");

                    b.ToTable("profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
